// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPlan(arg1) {
  return window['go']['main']['App']['BuildPlan'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function GetAppFeatures() {
  return window['go']['main']['App']['GetAppFeatures']();
}

export function GetBaiduConfig() {
  return window['go']['main']['App']['GetBaiduConfig']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function SaveBaiduConfig(arg1) {
  return window['go']['main']['App']['SaveBaiduConfig'](arg1);
}
