// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildPlan(arg1:main.PlanRequest):Promise<main.PlanResponse>;

export function ExportPDF(arg1:main.ExportRequest):Promise<main.ExportResponse>;

export function GetAppFeatures():Promise<main.AppFeatures>;

export function LoadImage(arg1:string):Promise<main.ImageInfo>;

export function OpenImageDialog():Promise<main.ImageInfo>;
